version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 12
    build:
        commands:
        - node --version
        - echo "Bucket name is ${S3BUCKET_ADMIN} and Stack name is ${STACKNAME}"
        - aws cloudformation describe-stacks --region ${REGION} --stack-name ${STACKNAME} > ./frontend/stackinfo.json
        - cd ./frontend/initial-config-script
        - npm install
        - node create-initial-config.js
        - cd ..
        - npm run update-env
        - npm install --legacy-peer-deps
        - npm install -g @angular/cli
        - npm run build
        - cd ..
    post_build:
        commands:
        - aws s3 sync --delete frontend/dist/aws-serverless-cms s3://${S3BUCKET_ADMIN}/scms --cache-control max-age=3600 --acl public-read
